### ISSUE TITLE
Fast scrolling error

### ISSUE THREAD

**Issue by Urdzik** [Urdzik/MovieApp#13]
### __When the user quickly scrolls through the list of films and clicks on the film to display detailed information about it. The application crashes with an error:__ 
```
2020-03-06 11:51:35.444 8213-8213/com.example.movieapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.movieapp, PID: 8213
    com.squareup.moshi.JsonDataException: Expected a string but was BEGIN_OBJECT at path $.belongs_to_collection
        at com.squareup.moshi.JsonUtf8Reader.nextString(JsonUtf8Reader.java:644)
        at com.squareup.moshi.StandardJsonAdapters$10.fromJson(StandardJsonAdapters.java:215)
        at com.squareup.moshi.StandardJsonAdapters$10.fromJson(StandardJsonAdapters.java:213)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:194)
        at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:156)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

```

**Comment by Urdzik** [comment]
This bug was fixed
